# Data preprocessing
VOCAB_SIZE = 8000
SEQUENCE_LENGTH = 30

# token tags
STARTOFSENTENCE_TOKEN = '<sos>'
ENDOFSENTENCE_TOKEN = '<eos>'
OUTOFVOCABULARY_TOKEN = '<oov>'

# Hyperparameters
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 100000
EPOCHS = 30
NUM_LAYERS = 2
NUM_HEADS = 8
D_MODEL = 256
UNITS = 512
DROPOUT = 0.1
