# Data preprocessing
VOCAB_SIZE = 8000
SEQUENCE_LENGTH = 30

# token tags
STARTOFSENTENCE_TOKEN = '<SOS>'
ENDOFSENTENCE_TOKEN = '<EOS>'
OUTOFVOCABULARY_TOKEN = '<OOV>'  # maybe not needed

# Hyperparameters
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 10000
EPOCHS = 20
NUM_LAYERS = 2
NUM_HEADS = 8
D_MODEL = 256
UNITS = 512
DROPOUT = 0.1
